/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#002107',
        'on-secondary-fixed': '#380039',
        'tertiary-fixed-dim': '#4cd6ff',
        'on-tertiary-fixed': '#001f28',
        'error-container': '#ffdad6',
        'surface-tint': '#006e27',
        'surface-bright': '#f9f9f9',
        'secondary-fixed-dim': '#ffaaf6',
        'on-tertiary-container': '#006a83',
        'inverse-surface': '#303030',
        'surface-variant': '#e2e2e2',
        'primary-fixed-dim': '#00e55b',
        error: '#ba1a1a',
        'on-surface-variant': '#3b4b3a',
        'outline-variant': '#b9ccb5',
        secondary: '#a800ab',
        'on-secondary': '#ffffff',
        'primary-container': '#00ff66',
        'inverse-primary': '#00e55b',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dadada',
        'on-primary-container': '#007128',
        'secondary-fixed': '#ffd7f6',
        'on-secondary-fixed-variant': '#800083',
        'on-tertiary-fixed-variant': '#004e60',
        'on-surface': '#1b1b1b',
        'surface-container': '#eeeeee',
        'tertiary-fixed': '#b7eaff',
        'tertiary-container': '#a8e7ff',
        outline: '#6b7c68',
        'surface-container-high': '#e8e8e8',
        'inverse-on-surface': '#f1f1f1',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f3f3f3',
        tertiary: '#00677f',
        'secondary-container': '#fc4afd',
        'on-secondary-container': '#5f0061',
        surface: '#f9f9f9',
        background: '#f9f9f9',
        primary: '#006e27',
        'primary-fixed': '#6bff83',
        'on-error': '#ffffff',
        'surface-container-highest': '#e2e2e2',
        'on-background': '#1b1b1b',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#00531b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'stroke-thick': '4px',
        'margin-desktop': '48px',
        gutter: '24px',
        'stroke-thin': '2px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        sans: ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      boxShadow: {
        neo: '4px 4px 0px 0px rgba(0,0,0,1)',
        'neo-lg': '8px 8px 0px 0px rgba(0,0,0,1)',
        'neo-sm': '2px 2px 0px 0px rgba(0,0,0,1)',
      },
    },
  },
  plugins: [],
}
